blogicum/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path(
        'category/<slug:category_slug>/',
        views.category_posts,
        name='category_posts'
    ),
    path(
        'profile/<str:username>/',
        views.ProfileDetailView.as_view(),
        name='profile'
    ),
    path(
        'profile/<str:username>/edit/',
        views.ProfileUpdateView.as_view(),
        name='edit_profile'
    ),
    path('posts/create/', views.PostCreateView.as_view(), name='create_post'),
    path(
        'posts/<int:pk>/',
        views.PostDetailView.as_view(),
        name='post_detail'
    ),
    path(
        'posts/<int:pk>/edit/',
        views.PostUpdateView.as_view(),
        name='edit_post'
    ),
    path(
        'posts/<int:pk>/delete/',
        views.PostDeleteView.as_view(),
        name='delete_post'
    ),
    path('posts/<int:pk>/comment/', views.add_comment, name='add_comment'),
    path(
        'posts/<int:pk>/edit_comment/<int:comment_pk>/',
        views.edit_comment,
        name='edit_comment'
    ),
    path(
        'posts/<int:post_id>/delete_comment/<int:comment_id>/',
        views.delete_comment,
        name='delete_comment'
    ),
]

blogicum/blogicum/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.processing_error'

auth_urls = [
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('blog:index'),
        ),
        name='registration',
    ),
]

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('pages/', include('pages.urls', namespace='pages')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
] + auth_urls + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogicum/templates/profile/edit_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  Редактирование профиля
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Редактирование профиля - {{ request.user }}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

blogicum/templates/profile/profile_form.html
{% extends "base.html" %}
{% block title %}
  Страница пользователя {{ profile }}
{% endblock %}
{% block content %}
  <h1 class="mb-5 text-center ">Страница пользователя {{ profile }}</h1>
  <small>
    <ul class="list-group list-group-horizontal justify-content-center mb-3">
      <li class="list-group-item text-muted">Имя пользователя: {% if profile.get_full_name %}{{ profile.get_full_name }}{% else %}не указано{% endif %}</li>
      <li class="list-group-item text-muted">Регистрация: {{ profile.date_joined }}</li>
      <li class="list-group-item text-muted">Роль: {% if profile.is_staff %}Админ{% else %}Пользователь{% endif %}</li>
    </ul>
    <ul class="list-group list-group-horizontal justify-content-center">
      {% if user.is_authenticated and request.user == profile %}
      <a class="btn btn-sm text-muted" href="{% url 'blog:edit_profile' profile.username %}">Редактировать профиль</a>
      <a class="btn btn-sm text-muted" href="{% url 'password_change' %}">Изменить пароль</a>
      {% endif %}
    </ul>
  </small>
  <br>
  <h3 class="mb-5 text-center">Публикации пользователя</h3>
  {% for post in page_obj %}
    <article class="mb-5">
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}